version: '3.7'

services:

  geolocation-api:
    container_name: geolocation-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    environment:
      ENV: 8080
      DB_NAME: geolocation
      DB_USER: example
      DB_PASS: example
    depends_on:
      - db
  db:
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_DB: geolocation
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
